### ISSUE TITLE
Login page "Error Loading Page'😢

### ISSUE THREAD

**Issue by McZobel** [rvolz/BicBucStriim#369]
Hello Mr. Volz,
i have install the BBS on a Synology NAS 918+.
The installcheck ist mostly green, but when want to log in the admin login the Error Loding Page Error occurs.
The Logfile show me this:

```
INFO - 2021-06-30T21:33:04+02:00 - BicBucStriim 1.5.0: Running in debug mode.
DEBUG - 2021-06-30T21:33:04+02:00 - caching_middleware: caching disabled for /login/
INFO - 2021-06-30T21:33:04+02:00 - multi user mode: login required
DEBUG - 2021-06-30T21:33:04+02:00 - own_config_middleware: config loaded
DEBUG - 2021-06-30T21:33:04+02:00 - login resource: /login/
DEBUG - 2021-06-30T21:33:04+02:00 - after resume: ANON
DEBUG - 2021-06-30T21:33:04+02:00 - login auth: NULL
DEBUG - 2021-06-30T21:33:04+02:00 - login: login page authorized
DEBUG - 2021-06-30T21:33:04+02:00 - mkRootUrl: Using root url 
INFO - 2021-06-30T21:33:08+02:00 - BicBucStriim 1.5.0: Running in debug mode.
DEBUG - 2021-06-30T21:33:08+02:00 - caching_middleware: caching disabled for /login/
INFO - 2021-06-30T21:33:08+02:00 - multi user mode: login required
DEBUG - 2021-06-30T21:33:08+02:00 - own_config_middleware: config loaded
ERROR - 2021-06-30T21:33:08+02:00 - ErrorException: Function get_magic_quotes_gpc() is deprecated in /volume1/web/bbs/vendor/slim/slim/Slim/Http/Util.php:60
Stack trace:
#0 /volume1/web/bbs/vendor/slim/slim/Slim/Http/Util.php(60): Slim\Slim::handleErrors(8192, 'Function get_ma...', '/volume1/web/bb...', 60, Array)
#1 /volume1/web/bbs/vendor/slim/slim/Slim/Http/Request.php(264): Slim\Http\Util::stripSlashesIfMagicQuotes(Array)
#2 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(86): Slim\Http\Request->post('_METHOD')
#3 /volume1/web/bbs/lib/BicBucStriim/calibre_config_middleware.php(54): Slim\Middleware\MethodOverride->call()
#4 /volume1/web/bbs/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#5 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#6 /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#7 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#8 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#9 /volume1/web/bbs/index.php(206): Slim\Slim->run()
#10 {main}
```

What do I wrong?

Sorry about my bad english...
Greets from Swabian 
Andreas

**Comment by rvolz** [comment]
Nothing, except that you are using PHP 7.4, which caused the problems. You can now download an update that works with PHP 7.4 from [here](http://projekte.textmulch.de/bicbucstriim/downloads/). Hope this helps

**Comment by McZobel** [comment]
Hi...your new archive is damaged...
I try it under MacOS HighSierra and Windows 10. Some folders cannot found.. 
can u check this
Thanks for you Help!
Andreas

**Comment by rvolz** [comment]
Right, the packaging library seems to be unreliable. I replaced it. Please try again.

**Comment by McZobel** [comment]
Hi ... now it works fine ... and it runs perfectly!
Thanks for your support!
Can I make a donation for your work!

I have a suggestion for improvement. It should be possible to specify an age for the user in order to hide books with certain keywords. (e.g. thriller and something else)  

Thankx 
Andreas

**Comment by pascal-louis** [comment]
Bonjour,

Juste pour mentionner que la version 1.5.3 proposée en téléchargement est en mode développement

Cordialement

Hello,

Just to mention that the version 1.5.3 proposed for download is in development mode

Sincerely

**Comment by rvolz** [comment]
Again? Sorry, I'll change that, *sigh* Thanks
