### ISSUE TITLE
#366 and #369 still present in debug (Function get_magic_quotes_gpc() is deprecated when logging in)

### ISSUE THREAD

**Issue by bkqc** [rvolz/BicBucStriim#382]
INFO - 2022-04-18T16:10:35-04:00 - BicBucStriim 1.5.3: Running in debug mode.
INFO - 2022-04-18T16:10:35-04:00 - Running on PHP: 7.4.9
DEBUG - 2022-04-18T16:10:35-04:00 - caching_middleware: caching disabled for /login/
INFO - 2022-04-18T16:10:35-04:00 - multi user mode: login required
DEBUG - 2022-04-18T16:10:35-04:00 - own_config_middleware: config loaded
DEBUG - 2022-04-18T16:10:35-04:00 - login resource: /login/
DEBUG - 2022-04-18T16:10:35-04:00 - after resume: ANON
DEBUG - 2022-04-18T16:10:35-04:00 - login auth: NULL
DEBUG - 2022-04-18T16:10:35-04:00 - login: login page authorized
DEBUG - 2022-04-18T16:10:35-04:00 - mkRootUrl: Using root url /bbs
INFO - 2022-04-18T16:10:45-04:00 - BicBucStriim 1.5.3: Running in debug mode.
INFO - 2022-04-18T16:10:45-04:00 - Running on PHP: 7.4.9
DEBUG - 2022-04-18T16:10:45-04:00 - caching_middleware: caching disabled for /login/
INFO - 2022-04-18T16:10:45-04:00 - multi user mode: login required
DEBUG - 2022-04-18T16:10:45-04:00 - own_config_middleware: config loaded
ERROR - 2022-04-18T16:10:45-04:00 - ErrorException: Function get_magic_quotes_gpc() is deprecated in /volume1/web/bbs/vendor/slim/slim/Slim/Http/Util.php:60
Stack trace:
#0 /volume1/web/bbs/vendor/slim/slim/Slim/Http/Util.php(60): Slim\Slim::handleErrors(8192, 'Function get_ma...', '/volume1/web/bb...', 60, Array)
#1 /volume1/web/bbs/vendor/slim/slim/Slim/Http/Request.php(264): Slim\Http\Util::stripSlashesIfMagicQuotes(Array)
#2 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(86): Slim\Http\Request->post('_METHOD')
#3 /volume1/web/bbs/lib/BicBucStriim/calibre_config_middleware.php(54): Slim\Middleware\MethodOverride->call()
#4 /volume1/web/bbs/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#5 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#6 /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#7 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#8 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#9 /volume1/web/bbs/index.php(210): Slim\Slim->run()
#10 {main}

**Comment by mikespub** [comment]
This was due to an outdated version of the slim/slim package included in the 1.5.3 release.

Updated in #391 and release 1.6.0 at https://github.com/mikespub-org/rvolz-BicBucStriim
